"""
Standardized error definitions and HTTP error responses.
"""

from enum import Enum

from pydantic import BaseModel, Field


class ErrorCode(str, Enum):
    PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND"
    REVISION_NOT_FOUND = "REVISION_NOT_FOUND"
    ANCHOR_NOT_FOUND = "ANCHOR_NOT_FOUND"
    ANCHOR_STALE = "ANCHOR_STALE"
    ELASTICSEARCH_UNAVAILABLE = "ELASTICSEARCH_UNAVAILABLE"
    INDEX_NOT_READY = "INDEX_NOT_READY"
    EMBEDDING_PROVIDER_UNAVAILABLE = "EMBEDDING_PROVIDER_UNAVAILABLE"
    LLM_PROVIDER_UNAVAILABLE = "LLM_PROVIDER_UNAVAILABLE"
    INVALID_AUTHOR_DECISION = "INVALID_AUTHOR_DECISION"
    CROSS_REVISION_CONFLICT = "CROSS_REVISION_CONFLICT"
    CROSS_PROJECT_MUTATION = "CROSS_PROJECT_MUTATION"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    UNSUPPORTED_IMPORT_FORMAT = "UNSUPPORTED_IMPORT_FORMAT"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    PARSING_ERROR = "PARSING_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


class ApiErrorDetail(BaseModel):
    code: ErrorCode
    message: str
    details: dict = Field(default_factory=dict)


class ApiErrorResponse(BaseModel):
    error: ApiErrorDetail
